### ISSUE TITLE
"ReferenceError: MutationObserver is not defined" on page reload

### ISSUE THREAD

**Issue by Feel2X** [andrew1007/react-on-images-loaded#21]
Hello,

thanks for your great work!

The onLoaded functions work as expected on the first time the page is loaded. However, when I reload the page (e.g. via the browser reload button), I receive the error message stated in the title and the page crashes.

I have not yet been able to handle this issue.

Best regards,
Felix

**Comment by andrew1007** [comment]
Apologies! Let me investigate

**Comment by andrew1007** [comment]
I'm not sure how reloading would affect your runtime in that way. Can you confirm what browser you are using? MutationObserver should be widely supported
https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver#browser_compatibility

**Comment by Feel2X** [comment]
> I'm not sure how reloading would affect your runtime in that way. Can you confirm what browser you are using? MutationObserver should be widely supported https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver#browser_compatibility

I have tested this for Chrome, Safari, and Firefox
I am using the onLoaded function in a Next.js application.

**Comment by andrew1007** [comment]
Oh, Next.js? Is the page that's crashing implemented with SSR? That would explain why `MutationObserver` may not be defined. Thanks for pointing this out. I'll patch it

**Comment by Feel2X** [comment]
Yes, the whole application is implemented with SSR, I almost assumed that this may be the issue.
Thank you, looking forward to your patch!

**Comment by andrew1007** [comment]
Done. Thanks for letting me know 👍
